### ISSUE TITLE
Additional funds in pool #3 locked when staking after voting

### ISSUE THREAD

**Issue by blockomoco** [iearn-finance/ygov-finance#11]
When voting, the currently staked funds in pool 3 (governance pool) are locked for some duration. So far so good.

Now, when one deposits and stakes additional funds to pool 3 after voting, the additional funds are locked as well. The UI in this case does not allow to unstake, indicating that one needs to wait until the lock period ends.

Is this a UI limitation or is unstaking indeed not possible for the additional funds ?
If unstaking not possible, is this intended behavior ?

I find this surprising. Better would be if only the amount is locked that was used to vote.

**Comment by antonnell** [comment]
UI is limiting it. It was to stop people from wasting gas when trying to unstake.
If you want to micromanage and unstake small portions while your vote is locked, interact with the smart contract directly.
