### ISSUE TITLE
Add reference to smart contracts

### ISSUE THREAD

**Issue by bgits** [iearn-finance/ygov-finance#13]
Where can one find the smart contracts that this front-end references?

If there is a github repo a submodule `contracts` would be useful but at least a link in README.md to the contracts.

**Comment by milkyklim** [comment]
You can refer to `List of Yearn Contracts` here: https://explore.duneanalytics.com/public/dashboards/cXCzl3KxsGeF9HoQQnZyNYWKGB63gXMqlow0hRrK 

I'll put any other contracts when they are deployed.

**Comment by yieldbouncer** [comment]
I can look into it. Just need to find a way to do it without cluster the UI

**Comment by bgits** [comment]
Are the contracts not developed using version control?

**Comment by milkyklim** [comment]
If you don't find them in the [org](https://github.com/iearn-finance) then no.
