### ISSUE TITLE
Add feedback on vote

### ISSUE THREAD

**Issue by milkyklim** [iearn-finance/ygov-finance#14]
People complain that there is no feedback after voting and it is not clear if they voted or not:

https://gov.yearn.finance/t/yearn-interaction-feedback/1321/3?u=milkyklim
https://gov.yearn.finance/t/yearn-interaction-feedback/1321/4?u=milkyklim

**Comment by mariuspod** [comment]
Hi, I had the same issues, so I've created a PR:
https://github.com/iearn-finance/ygov-finance/pull/20
