### ISSUE TITLE
Adding list of voted proposas to vote page

### ISSUE THREAD

**Issue by dmolina79** [iearn-finance/ygov-finance#19]
Reference:

https://twitter.com/iamDCinvestor/status/1300071438477557761?s=20

Maybe show a third option along with done and open of "Voted"

![Screen Shot 2020-08-31 at 7 55 10 PM](https://user-images.githubusercontent.com/6074987/91787287-c20e7200-ebc6-11ea-81b2-ef46ab3b3d2c.png)

I think this subgraph can be used to get the list of ballots a voter has participated on
https://thegraph.com/explorer/subgraph/crazyrabbitltc/yearngovernance
Since don't see at quick glance if the contract has a query option for this.

**Comment by dmolina79** [comment]
I'll take a shot at this if i can add the subgraph to the store

**Comment by mariuspod** [comment]
Hi, I've created a PR here:
https://github.com/iearn-finance/ygov-finance/pull/20

It shows the vote status inside the proposals component. 
I've just seen your comment when I was done with coding.
