### ISSUE TITLE
Let users know via the ui that their staked YFI will be locked 3 days before voting

### ISSUE THREAD

**Issue by DarkGhost7** [iearn-finance/ygov-finance#21]
Make it apparent in the UI before voting that this action will lock their YFI for 3 days.

**Comment by mariuspod** [comment]
It's here for review: https://github.com/iearn-finance/ygov-finance/pull/22

**Comment by saltyfacu** [comment]
This is not applicable anymore. Voting takes place on snapshot @milkyklim
