### ISSUE TITLE
Add proposal deadlines to UI

### ISSUE THREAD

**Issue by milkyklim** [iearn-finance/ygov-finance#6]
> Hi mods - can you add the voting deadline for each proposal once it goes on-chain? This is important information and it is missing both from the forums and https://ygov.finance/vote

Source: https://gov.yearn.finance/t/proposal-deadlines-missing/364

**Comment by antonnell** [comment]
Closed by 1371c4cb1b92cc4ef12841f8d8e86bfee2a7cccb
